# Generated by Django 6.0.4 on 2026-04-25 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPadCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория iPad",
                "verbose_name_plural": "Категории iPad",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("text", models.TextField(max_length=5000, verbose_name="Отзыв")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPadModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название модели"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ipads/",
                        verbose_name="Изображение",
                    ),
                ),
                ("display", models.CharField(max_length=200, verbose_name="Дисплей")),
                (
                    "processor",
                    models.CharField(max_length=100, verbose_name="Процессор"),
                ),
                ("memory", models.CharField(max_length=100, verbose_name="Память")),
                ("camera", models.CharField(max_length=200, verbose_name="Камера")),
                ("battery", models.CharField(max_length=100, verbose_name="Батарея")),
                ("weight", models.CharField(max_length=50, verbose_name="Вес")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата выхода"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ipad_app.ipadcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "iPad",
                "verbose_name_plural": "iPad'ы",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipad_model",
                    models.CharField(
                        choices=[
                            ("pro", "iPad Pro"),
                            ("air", "iPad Air"),
                            ("mini", "iPad mini"),
                            ("base", "iPad (базовая модель)"),
                        ],
                        max_length=10,
                        verbose_name="Модель iPad",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Ключ сессии"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата голосования"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Голос",
                "verbose_name_plural": "Голоса",
            },
        ),
    ]
